/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.fatec.questionario;

import org.apache.catalina.connector.Connector;
import org.apache.coyote.ajp.AjpNioProtocol;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.core.io.ClassPathResource;
import org.springframework.util.ResourceUtils;

import java.io.File;
import java.nio.file.Files;

@SpringBootApplication
@EnableAutoConfiguration
@ComponentScan(basePackages= {"edu.fatec.questionario.controller", "edu.fatec.questionario.services"})
public class Questionarios {
    @Value("${tomcat.ajp.port}")
    int ajpPort;

    @Value("${tomcat.ajp.remoteauthentication}")
    String remoteAuthentication;

    @Value("${tomcat.ajp.enabled}")
    boolean tomcatAjpEnabled;

    @Value("${QUESTIONARIOS_PATH:/var/www/rh.dsmzl.tec.br}")
    private String assetsPath;


    public static void main(String[] args) {
        SpringApplication.run(Questionarios.class, args);
    }


    @Bean
    public CommandLineRunner CommandLineRunnerBean() {
        return (args) -> {

            System.out.println("VARIAVEL DE DIRETORIO ==> " + assetsPath);

            // File file = ResourceUtils.getFile("classpath:json/aguia.json");
//            File file1 = new ClassPathResource("" +
//                    "config/json/aguia.json").getFile();
//            System.out.println("File Found ClassPathResource: " + file1.exists());

//            File file2 = ResourceUtils.getFile("classpath:config/json/aguia.json");
//            System.out.println("File Found ResourceUtils: " + file2.exists());
//            String content = new String(Files.readAllBytes(file.toPath()));
//            System.out.println(content);
        };
    }

    @Bean
    public TomcatServletWebServerFactory servletContainer() {

        TomcatServletWebServerFactory tomcat = new TomcatServletWebServerFactory();
        if (tomcatAjpEnabled)
        {
            Connector ajpConnector = new Connector("org.apache.coyote.ajp.AjpNioProtocol");
            AjpNioProtocol protocol= (AjpNioProtocol)ajpConnector.getProtocolHandler();
            protocol.setSecret("myapjsecret");
            ajpConnector.setPort(ajpPort);
            ajpConnector.setSecure(true);
            ajpConnector.setAllowTrace(false);
            ajpConnector.setScheme("https");
            tomcat.addAdditionalTomcatConnectors(ajpConnector);
        }

        return tomcat;
    }

}

