/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cpb.cursos.controller;

import cpb.cursos.model.*;
import cpb.cursos.services.ElementoService;
import cpb.cursos.services.QuestionarioService;
import cpb.cursos.util.QuestionarioUtil;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.stereotype.Controller;
import org.springframework.util.MultiValueMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;

@Controller
@EnableAutoConfiguration
public class QuestionarioController {

	private final QuestionarioService questionarioService;
	private final ElementoService elementoService;
	private final LanguageUtils languageUtils;

	
	public List<SecaoDTO> generateListCategoriaDTO(List<Secao> secoes) {
		List<SecaoDTO> secaoDTO = new ArrayList<>();
		for (Secao secao : secoes) {
			SecaoDTO catDTO = secao.generateDTO();
			List<Elemento> elementos = elementoService.procurarPorSecao(secao);
			for (Elemento elemento : elementos) {
				catDTO.getRespostas().add(elemento);
			}
			secaoDTO.add(catDTO);
		}
		return secaoDTO;
	}
    
    public QuestionarioController(ElementoService elementoService,
								  QuestionarioService questionarioService,
								  LanguageUtils languageUtils) {
		this.elementoService = elementoService;
		this.questionarioService = questionarioService;
		this.languageUtils = languageUtils;
	}
    
    public static Elemento findPerguntaById(Collection<Elemento> listElemento, long id) {
        return listElemento.stream().filter(pergunta -> pergunta.getId() == id).findFirst().orElse(null);
    }

	@GetMapping(path = {"/questionario/{questionario}"})
    public ModelAndView questionarioGet(@PathVariable("questionario") String questionarioNome) {
		Questionario questionario = questionarioService.retrieveQuestionarioPorNome(questionarioNome);
		ModelAndView mv = new ModelAndView();
		if (questionario != null) {
			// Define os numero das questões
			int indiceQuestao = 0;
			for (Elemento e : questionario.getElementos()) {
				if (QuestionarioUtil.isPergunta(e) && !e.getTipo().equals("labelInputTextSemNumero")) {
					e.setNumeroQuestao(++indiceQuestao);
				}
			}
			mv.setViewName("questionario");
			mv.addObject("questionario", questionario);
			mv.addObject("questionarioNome", questionarioNome);
			mv.addObject("languageUtils", languageUtils);
			// System.out.println("Language Utils Lista Gerada: " + languageUtils.getLista().toString());
		} else {
			mv.setViewName("inexistente");
		}
    	return mv;
    }
	
	@PostMapping(path = {"/questionario/{questionario}"})
    public ModelAndView questionarioPost(	@PathVariable("questionario") String questionarioNome,
											@RequestParam MultiValueMap<String, String> allParams) {
		Questionario questionario = questionarioService.retrieveQuestionarioPorNome(questionarioNome);
		if (questionario != null) {
			QuestionarioResposta questionarioResposta = new QuestionarioResposta(questionario);
			// System.out.println("Post acionado: " + questionarioResposta.getId());
			for (String paramName : allParams.keySet()) {
				for (Resposta resp : questionarioResposta.getRespostas()) {
					System.out.println("Analisando resposta: " + resp.getVariavel());
					if (resp.getVariavel().equals(paramName)) {
						List<String> params = allParams.get(paramName);
						if (params.size() > 1) {
							resp.setValor(LanguageUtils.consolidateList(params));
						} else {
							resp.setValor(allParams.getFirst(paramName));
						}
						// System.out.println("Resposta definida: " + paramName + "  Valor: " + resp.getValor());
					}
				}
			}

			List<Resposta> respostasNome = QuestionarioUtil.procurarRespostaPeloTipo(questionarioResposta, "contatoNome");
			if (!respostasNome.isEmpty()) {
				questionarioResposta.getContato().setNome(respostasNome.get(0).getValor());
			}

			List<Resposta> respostasEmail = QuestionarioUtil.procurarRespostaPeloTipo(questionarioResposta, "contatoEmail");
			if (!respostasEmail.isEmpty()) {
				questionarioResposta.getContato().setEmail(respostasEmail.get(0).getValor());
			}
			questionarioService.salvarQuestionarioRespostas(questionarioResposta);
		}
		ModelAndView mv = new ModelAndView("sucesso");
		mv.addObject("mensagem", "Questionário gravado com sucesso");
		return mv;
	}
}
