/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.fatec.questionario.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import edu.fatec.questionario.model.*;
import edu.fatec.questionario.services.ElementoService;
import edu.fatec.questionario.services.ProcessaQuestionario;
import edu.fatec.questionario.services.ProcessaResposta;
import edu.fatec.questionario.services.QuestionarioService;
import edu.fatec.questionario.util.QuestionarioUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.core.io.ResourceLoader;
import org.springframework.stereotype.Controller;
import org.springframework.util.MultiValueMap;
import org.springframework.util.ResourceUtils;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.core.io.ClassPathResource;
import org.yaml.snakeyaml.util.ArrayUtils;

import javax.servlet.ServletContext;
import java.io.*;
import java.lang.reflect.Array;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;

@Controller
@EnableAutoConfiguration
public class QuestionarioController {

	private final QuestionarioService questionarioService;
	private final ElementoService elementoService;
	private final LanguageUtils languageUtils;

	@Value("${QUESTIONARIOS_PATH:/var/www/rh.dsmzl.tec.br}")
	private String assetsPath;

	@Autowired
	private ResourceLoader resourceLoader;

	@Autowired
	private ServletContext servletContext;
	private final Map<String, Integer> summaryResponses = new HashMap<>();
	private final Map<String, ProcessaResposta> engineResponses = new HashMap<>();
	private final Map<String, ProcessaQuestionario> engineQuestionarioBefore = new HashMap<>();
	private final Map<String, ProcessaQuestionario> engineQuestionarioAfter = new HashMap<>();
	private final Map<String, Object> contextQuestionario = new HashMap<>();
	private String mensagemResultado = "";
	private int totalGeralPontosRadioLabel = 0;

	static class AnimalInfo {
		private float porcentagem;
		private int porcentagemInteira;
		private String fileName;
		private String key;
		private String lema;
		private String titulo;
		private List<String> descricao = new ArrayList<>();
		private List<String> comportamentos = new ArrayList<>();
		private List<String> pontosfortes = new ArrayList<>();
		private List<String> pontosmelhoria = new ArrayList<>();
		private List<String> motivacoes = new ArrayList<>();

		public AnimalInfo() {
			this("", "", 0);
		}

		public AnimalInfo(String key, String fileName, float porcentagem) {
			this.key = key;
			this.setPorcentagem(porcentagem);
			this.fileName = fileName;
		}

		public float getPorcentagem() {
			return porcentagem;
		}

		public void setPorcentagem(float porcentagem) {
			this.porcentagem = porcentagem;
			this.porcentagemInteira = (int)(this.porcentagem * 100);
		}

		public int getPorcentagemInteira() {
			return porcentagemInteira;
		}

		public String getFileName() {
			return fileName;
		}

		public void setFileName(String fileName) {
			this.fileName = fileName;
		}

		public String getKey() {
			return key;
		}

		public void setKey(String key) {
			this.key = key;
		}

		public String getLema() {
			return lema;
		}

		public void setLema(String lema) {
			this.lema = lema;
		}

		public String getTitulo() {
			return titulo;
		}

		public void setTitulo(String titulo) {
			this.titulo = titulo;
		}

		public List<String> getDescricao() {
			return descricao;
		}

		public void setDescricao(List<String> descricao) {
			this.descricao = descricao;
		}

		public List<String> getComportamentos() {
			return comportamentos;
		}

		public void setComportamentos(List<String> comportamentos) {
			this.comportamentos = comportamentos;
		}

		public List<String> getPontosfortes() {
			return pontosfortes;
		}

		public void setPontosfortes(List<String> pontosfortes) {
			this.pontosfortes = pontosfortes;
		}

		public List<String> getPontosmelhoria() {
			return pontosmelhoria;
		}

		public void setPontosmelhoria(List<String> pontosmelhoria) {
			this.pontosmelhoria = pontosmelhoria;
		}

		public List<String> getMotivacoes() {
			return motivacoes;
		}

		public void setMotivacoes(List<String> motivacoes) {
			this.motivacoes = motivacoes;
		}

		public void copyFrom(AnimalInfo readValue) {
			this.setLema(readValue.getLema());
			this.setTitulo(readValue.getTitulo());
			this.setDescricao(readValue.getDescricao());
			this.setComportamentos(readValue.getComportamentos());
			this.setPontosfortes(readValue.getPontosfortes());
			this.setPontosmelhoria(readValue.getPontosmelhoria());
			this.setMotivacoes(readValue.getMotivacoes());
		}
	}

	void generateProcessorEngines() {
		engineQuestionarioBefore.put("RESET", q -> {
			summaryResponses.clear();
			summaryResponses.put("A", 0);
			summaryResponses.put("I", 0);
			summaryResponses.put("O", 0);
			summaryResponses.put("C", 0);
			totalGeralPontosRadioLabel = 0;
			return true;
		});



		engineResponses.put("SUMMARIZE_RADIO", r-> {
			if ("radioLabelValue".equals(r.getTipo()) &&
					Arrays.asList("A", "I", "O", "C").contains(r.getValor())) {
				if (summaryResponses.containsKey(r.getValor())) {
					int total = summaryResponses.get(r.getValor());
					summaryResponses.put(r.getValor(), total + 1);
				} else {
					summaryResponses.put(r.getValor(), 1);
				}
				totalGeralPontosRadioLabel += 1;
			}
			return true;
		});

		engineQuestionarioAfter.put("SHOW_INFO", q -> {

			List<AnimalInfo> animals = new ArrayList<>();

			animals.add(new AnimalInfo("A", "tubarao", ((float) summaryResponses.get("A") / (float) totalGeralPontosRadioLabel)));
			animals.add(new AnimalInfo("C", "gato", ((float) summaryResponses.get("C") / (float) totalGeralPontosRadioLabel)));
			animals.add(new AnimalInfo("I", "aguia", ((float) summaryResponses.get("I") / (float) totalGeralPontosRadioLabel)));
			animals.add(new AnimalInfo("O", "lobo", ((float) summaryResponses.get("O") / (float) totalGeralPontosRadioLabel)));

			animals.sort(Comparator.comparing(AnimalInfo::getPorcentagem));

			ObjectMapper objectMapper = new ObjectMapper();
			LinkedList<AnimalInfo> animais = new LinkedList<>();
			animals.forEach(animais::push);

			for (AnimalInfo a : animais) {
				try {
					File file = null;
					try {
						file = new ClassPathResource(String.format("config/json/%s.json", a.getFileName())).getFile();
					} catch (Exception e) {
						String fileName = String.format(assetsPath + "/json/%s.json", a.getFileName());
						Path path = ResourceUtils.getFile(fileName).toPath();
						file = path.toFile();
					}
					FileInputStream fileIs = new FileInputStream(file);
					BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(fileIs, "UTF-8"));
					String json = bufferedReader.lines().collect(Collectors.joining("\n"));
					// below line is for conversion
					AnimalInfo animalTemp = objectMapper.readValue(json, AnimalInfo.class);
					a.copyFrom(animalTemp);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
			contextQuestionario.put("animais", animais);

			mensagemResultado = animais.stream()
					.map(a -> String.format("\tPorcentagem %s é %d%%", a.titulo, a.getPorcentagemInteira()))
					.collect( Collectors.joining( "<br/>\n" ) );
			contextQuestionario.put("mensagemAnimais", mensagemResultado);
			System.out.println(summaryResponses);
			System.out.println(mensagemResultado);
			return true;
		});
	}

	@GetMapping(path = {"/questionario/teste"})
	public String teste() {
		String animalFile = "aguia";
		System.out.println("Assets Path ==> " + assetsPath);
		try {
			String fileName2 = String.format(assetsPath + "/json/%s.json", animalFile);
			Path path = ResourceUtils.getFile(fileName2).toPath();
			File file = path.toFile();
			FileInputStream fileIs = new FileInputStream( file );
			BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(fileIs));
			System.out.println(bufferedReader.lines().collect(Collectors.joining("\n")));
		} catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println("### Teste acionado");
		return "inexistente";
	}
	
	public List<SecaoDTO> generateListCategoriaDTO(List<Secao> secoes) {
		List<SecaoDTO> secaoDTO = new ArrayList<>();
		for (Secao secao : secoes) {
			SecaoDTO catDTO = secao.generateDTO();
			List<Elemento> elementos = elementoService.procurarPorSecao(secao);
			for (Elemento elemento : elementos) {
				catDTO.getRespostas().add(elemento);
			}
			secaoDTO.add(catDTO);
		}
		return secaoDTO;
	}
    
    public QuestionarioController(ElementoService elementoService,
								  QuestionarioService questionarioService,
								  LanguageUtils languageUtils) {
		this.elementoService = elementoService;
		this.questionarioService = questionarioService;
		this.languageUtils = languageUtils;
		generateProcessorEngines();
	}
    
    public static Elemento findPerguntaById(Collection<Elemento> listElemento, long id) {
        return listElemento.stream().filter(pergunta -> pergunta.getId() == id).findFirst().orElse(null);
    }

	@GetMapping(path = {"/questionario/{questionario}"})
    public ModelAndView questionarioGet(@PathVariable("questionario") String questionarioNome) {
		Questionario questionario = questionarioService.retrieveQuestionarioPorNome(questionarioNome);
		ModelAndView mv = new ModelAndView();
		System.out.println("### questionarioGet - Acessado: " + questionarioNome);
		if (questionario != null) {
			// Define os numero das questões
			int indiceQuestao = 0;
			for (Elemento e : questionario.getElementos()) {
				if (QuestionarioUtil.isPergunta(e) && !e.getTipo().equals("labelInputTextSemNumero")) {
					e.setNumeroQuestao(++indiceQuestao);
				}
			}
			mv.setViewName("questionario");
			mv.addObject("questionario", questionario);
			mv.addObject("questionarioNome", questionarioNome);
			mv.addObject("languageUtils", languageUtils);
			// System.out.println("Language Utils Lista Gerada: " + languageUtils.getLista().toString());
		} else {
			mv.setViewName("inexistente");
		}
    	return mv;
    }
	
	@PostMapping(path = {"/questionario/{questionario}"})
    public ModelAndView questionarioPost(	@PathVariable("questionario") String questionarioNome,
											@RequestParam MultiValueMap<String, String> allParams) {
		Questionario questionario = questionarioService.retrieveQuestionarioPorNome(questionarioNome);
		mensagemResultado = "Questionario gravado com sucesso";
		ModelAndView mv = new ModelAndView("resultado");
		if (questionario != null) {
			// processa questionarios after
			for ( String engine :  engineQuestionarioBefore.keySet()) {
				ProcessaQuestionario proc = engineQuestionarioBefore.get(engine);
				proc.processa(questionario);
			}

			QuestionarioResposta questionarioResposta = new QuestionarioResposta(questionario);
			// System.out.println("Post acionado: " + questionarioResposta.getId());
			for (String paramName : allParams.keySet()) {
				for (Resposta resp : questionarioResposta.getRespostas()) {
					// System.out.println("Analisando resposta: " + resp.getVariavel());
					if (resp.getVariavel().equals(paramName)) {
						List<String> params = allParams.get(paramName);
						if (params.size() > 1) {
							resp.setValor(LanguageUtils.consolidateList(params));
						} else {
							resp.setValor(allParams.getFirst(paramName));
						}

						// processa respostas por engines
						for ( String engine :  engineResponses.keySet()) {
							ProcessaResposta proc = engineResponses.get(engine);
							proc.processa(resp);
						}

						// System.out.println("Resposta definida: " + paramName + "  Valor: " + resp.getValor());
					}
				}
			}

			// processa questionarios after
			for ( String engine :  engineQuestionarioAfter.keySet()) {
				ProcessaQuestionario proc = engineQuestionarioAfter.get(engine);
				proc.processa(questionario);
			}

			List<Resposta> respostasNome = QuestionarioUtil.procurarRespostaPeloTipo(questionarioResposta, "contatoNome");
			if (!respostasNome.isEmpty()) {
				questionarioResposta.getContato().setNome(respostasNome.get(0).getValor());
			}

			List<Resposta> respostasEmail = QuestionarioUtil.procurarRespostaPeloTipo(questionarioResposta, "contatoEmail");
			if (!respostasEmail.isEmpty()) {
				questionarioResposta.getContato().setEmail(respostasEmail.get(0).getValor());
			}

			List<Resposta> respostasTelefone = QuestionarioUtil.procurarRespostaPelaVariavel(questionarioResposta, "contatoTelefone");
			if (!respostasTelefone.isEmpty()) {
				questionarioResposta.getContato().setTelefone(respostasTelefone.get(0).getValor());
			}

			List<Resposta> respostasGenero = QuestionarioUtil.procurarRespostaPelaVariavel(questionarioResposta, "genero");
			if (!respostasGenero.isEmpty()) {
				questionarioResposta.getContato().setGenero(respostasGenero.get(0).getValor());
			}

			List<Resposta> respostasCurso = QuestionarioUtil.procurarRespostaPelaVariavel(questionarioResposta, "curso");
			if (!respostasCurso.isEmpty()) {
				questionarioResposta.getContato().setCurso(respostasCurso.get(0).getValor());
			}

			questionarioResposta.getContato().setIdOrigem(questionario.getId());

			questionarioService.salvarQuestionarioRespostas(questionarioResposta);

			mv.addObject("contextQuestionario", contextQuestionario);
			mv.addObject("questionarioResposta", questionarioResposta);
		}
		mv.addObject("mensagem", mensagemResultado);
		return mv;
	}
}
